[tool.poetry]
name = "rnsh"
version = "0.0.1"
description = "Shell over Reticulum"
authors = ["acehoss <acehoss@acehoss.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rns = {git = "https://github.com/markqvist/Reticulum.git", rev = "3706769"}
docopt = "^0.6.2"
psutil = "^5.9.4"

[tool.poetry.scripts]
rnsh = 'rnsh.rnsh:rnsh_cli'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
